# Site settings
title: Secret Escapes

core-se-link: https://www.secretescapes.com/current-sales
description:

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/email" # the subpath of your site, e.g. /blog/
img:     "/email/_assets/img"
css:     "/email/_assets/css"
js:      "/email/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed